const availablePermission = [
    { name: "Super Admin Dashboard", permission: "SuperDashboard" },
    { name: "Manager Dashboard", permission: "managerDashboard" },
    { name: "Employee Dashboard", permission: "employeeDashboard" },
    { name: "View Policies", permission: "viewPolicies" },
    { name: "Update Policies", permission: "PolicySystem" },
    { name: "Post Orientation", permission: "postInduction" },
    { name: "View Orientation", permission: "viewInduction" },
    { name: "Super Admin Add Employee", permission: "addEmployeeAdmin" },
    { name: "Manager Add Employee", permission: "addEmployeeManager" },
    {
      name: "Super Admin Update Employee",
      permission: "updateEmployeeAdmin",
    },
    { name: "Manager Update Employee", permission: "updateEmployeeManager" },
    { name: "Delete Employee", permission: "deleteEmployeeAdmin" },
    { name: "View Employee", permission: "viewEmployeeAdmin" },
    {
      name: "Active/Inactive Employee",
      permission: "active/InactiveEmployeeAdmin",
    },
    { name: "Organization Chart", permission: "organizationChart" },
    { name: "View Daily Tasks", permission: "ViewTaskManager" },
    { name: "Update Daily Tasks", permission: "updateTask" },
    { name: "Job Posting", permission: "jobPostingAdmin" },
    { name: "Job Management", permission: "jobVacancyAdmin" },
    { name: "View Job Vacanies", permission: "viewVacancies" },
    { name: "View All Issue", permission: "IssueManagementSuperAdmin" },
    { name: "Raise A Issue", permission: "getSupport" },
    { name: "Issues Management", permission: "manageIssuesAdmin" },
    { name: "Assign Task", permission: "ActionTrackerManager" },
    { name: "View Task Assigned", permission: "actionTracker" },
    { name: "RACI Business", permission: "Raci2" },
    { name: "RACI OPS", permission: "superAdminRaci" },
    { name: "Payroll Management", permission: "payroll" },
    { name: "View My Profile", permission: "viewProfile" },
    { name: "Post Announcement", permission: "AddAnnouncement" },
    { name: "View Attendance & Payroll", permission: "myAttendance" },
    { name: "Training Material", permission: "trainingMaterial" },
    {
      name: "Add Department ",
      permission: "superAdminDepartmentDesignation",
    },
    { name: "Company Overview", permission: "CompanySettings" },
    { name: "Apply Leave Employee", permission: "applyLeaves" },
    { name: "Apply Leave Manager", permission: "acceptandrejectleave" },
    { name: "Employee Leave History", permission: "viewLeaves" },
    { name: "Attendance View", permission: "viewAttendance" },
    { name: "All Employes", permission: "updateEmployeeSuperAdmin" },
    { name: "Rate Subordinate", permission: "rateSubordinate" },
    {
      name: "View Subordinate Ratings",
      permission: "viewSubordinateRatings",
    },
    { name: "All Employes Rating", permission: "viewAllEmployeeRatings" },
    { name: "Post Top Performer", permission: "postTopPerformer" },
    { name: "View Top Performers Employes", permission: "viewTopPerformers" },
    { name: "Company Info", permission: "companyInfo" },
    { name: "Add Role", permission: "addRole" },
    { name: "Add Designation", permission: "addDesignation" },
    { name: "Set KPIs", permission: "setKPIs" },
    { name: "Asset", permission: "assignAssets" },
    { name: "Submit Resignation", permission: "submitResignation" },
    { name: "Resignation Dashboard", permission: "employeeResignationDashboard" },
    { name: "Resignation Approvals", permission: "hrResignationDashboard" },
    { name: "HR FNF Approvals", permission: "FNFAprroval" },
    { name: "All Resignation History", permission: "viewAllResignation" },
    { name: "POSH Employee", permission: "poshEmployee" },
    { name: "POSH Manager", permission: "poshManager" },
    { name: "HR Referral Dashboard", permission: "HRreferralDashboard" },
    {
      name: "Employee Referral Dashboard",
      permission: "EmployeereferralDashboard",
    },
    {
      name: "View Engagement Dashboard",
      permission: "engagement",
    },
    {
      name: "Engagement Permission Dashboard",
      permission: "engagementManager",
    },
  ];
  
  const availablePermissionManager = [
    { name: "Manager Dashboard", permission: "managerDashboard" },
    { name: "Employee Dashboard", permission: "employeeDashboard" },
    { name: "View Policies", permission: "viewPolicies" },
    { name: "Update Policies", permission: "PolicySystem" },
    { name: "Post Orientation", permission: "postInduction" },
    { name: "View Orientation", permission: "viewInduction" },
    // { name: "Super Admin Add Employee", permission: "addEmployeeAdmin" },
    { name: "Manager Add Employee", permission: "addEmployeeManager" },
    // { name: "Super Admin Update Employee", permission: "updateEmployeeAdmin" },
    { name: "Manager Update Employee", permission: "updateEmployeeManager" },
    { name: "View Employee", permission: "viewEmployeeAdmin" },
    {
      name: "Active/Inactive Employee",
      permission: "active/InactiveEmployeeAdmin",
    },
    { name: "Organization Chart", permission: "organizationChart" },
    { name: "View Daily Tasks", permission: "ViewTaskManager" },
    { name: "Update Daily Tasks", permission: "updateTask" },
    { name: "Job Posting", permission: "jobPostingAdmin" },
    { name: "Job Management", permission: "jobVacancyAdmin" },
    { name: "View Job Vacanies", permission: "viewVacancies" },
    // { name: "View All Issue", permission: "IssueManagementSuperAdmin" },
    { name: "Raise A Issue", permission: "getSupport" },
    { name: "Issues Management", permission: "manageIssuesAdmin" },
    { name: "Assign Task", permission: "ActionTrackerManager" },
    { name: "View Task Assigned", permission: "actionTracker" },
    { name: "RACI Business", permission: "Raci2" },
    { name: "RACI OPS", permission: "superAdminRaci" },
    { name: "Payroll Management", permission: "payroll" },
    { name: "View My Profile", permission: "viewProfile" },
    { name: "Post Announcement", permission: "AddAnnouncement" },
    { name: "View Attendance & Payroll", permission: "myAttendance" },
    { name: "Training Material", permission: "trainingMaterial" },
    { name: "Apply Leave Employee", permission: "applyLeaves" },
    { name: "Apply Leave Manager", permission: "acceptandrejectleave" },
    { name: "Employee Leave History", permission: "viewLeaves" },
    { name: "Attendance View", permission: "viewAttendance" },
    // { name: "All Employes", permission: "updateEmployeeSuperAdmin" },
    { name: "Rate Subordinate", permission: "rateSubordinate" },
    { name: "View Subordinate Ratings", permission: "viewSubordinateRatings" },
    { name: "All Employes Rating", permission: "viewAllEmployeeRatings" },
    { name: "Post Top Performer", permission: "postTopPerformer" },
    { name: "View Top Performers Employes", permission: "viewTopPerformers" },
    // { name: "Add Role", permission: "addRole" },
    // { name: "Add Designation", permission: "addDesignation" },
    { name: "Set KPIs", permission: "setKPIs" },
    { name: "Asset", permission: "assignAssets" },
    { name: "Submit Resignation", permission: "submitResignation" },
    { name: "Resignation Dashboard", permission: "employeeResignationDashboard" },
    { name: "Resignation Approvals", permission: "hrResignationDashboard" },
    { name: "HR FNF Approvals", permission: "FNFAprroval" },
    { name: "All Resignation History", permission: "viewAllResignation" },
    { name: "POSH Employee", permission: "poshEmployee" },
    { name: "POSH Manager", permission: "poshManager" },
    { name: "HR Referral Dashboard", permission: "HRreferralDashboard" },
    {
      name: "Employee Referral Dashboard",
      permission: "EmployeereferralDashboard",
    },
  ];
  
  export { availablePermission, availablePermissionManager };
  